# Generated by Django 5.0.7 on 2025-07-26 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='identificador',
            field=models.CharField(default='8DDQB7FD', max_length=8, unique=True),
        ),
    ]
