# Generated by Django 5.0.7 on 2025-07-26 05:00

import citas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0002_cita_identificador'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='identificador',
            field=models.CharField(default=citas.models.id, max_length=8, unique=True),
        ),
    ]
