# Generated by Django 5.0.7 on 2025-07-28 05:44

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0005_alter_cita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(validators=[django.core.validators.MinValueValidator(datetime.datetime(2025, 7, 28, 1, 44, 14, 833936))]),
        ),
    ]
