# Generated by Django 5.0.7 on 2025-07-28 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0006_alter_cita_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(),
        ),
        migrations.AddConstraint(
            model_name='cita',
            constraint=models.UniqueConstraint(fields=('fecha', 'barbero'), name='unique_barbero_fecha', violation_error_message='Ya existe una cita para este barbero a esta fecha y hora.'),
        ),
    ]
