# Generated by Django 5.0.7 on 2025-07-28 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0007_alter_cita_fecha_cita_unique_barbero_fecha'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='cita',
            name='unique_barbero_fecha',
        ),
    ]
