# Generated by Django 5.0.7 on 2025-07-29 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0008_remove_cita_unique_barbero_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='notas',
            field=models.TextField(max_length=255, null=True),
        ),
    ]
