# Generated by Django 5.0.7 on 2025-07-29 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0009_cita_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='notas',
            field=models.TextField(blank=True, max_length=255, null=True),
        ),
    ]
