# Generated by Django 5.0.7 on 2025-08-04 04:43

import citas.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0010_alter_cita_notas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita',
            name='fecha',
            field=models.DateTimeField(validators=[citas.models.validar_fecha_futura]),
        ),
    ]
