# Generated by Django 5.2.5 on 2025-08-15 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0011_alter_cita_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='cliente_apellido',
            field=models.CharField(default='.', max_length=100),
            preserve_default=False,
        ),
    ]
