# Generated by Django 5.2.5 on 2025-08-15 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('citas', '0012_cita_cliente_apellido'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cita',
            name='cliente_apellido',
        ),
    ]
